modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/Mrbysco/DistantFriends/issues"
license="MIT"

[[mods]]
modId="distantfriends"
version="${file.jarVersion}"
displayName="Distant Friends"
displayURL="https://www.curseforge.com/minecraft/mc-mods/distantfriends"
authors="Mrbysco, ShyNieke"
description='''
Don't mind them, they just like looking at you
'''
[[dependencies.distantfriends]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"