modLoader="javafml"
loaderVersion="[3,)"
issueTrackerURL="https://github.com/Mrbysco/DistantFriends/issues"
license="MIT"

[[mods]]
modId="distantfriends"
version="${file.jarVersion}"
displayName="Distant Friends"
displayURL="https://www.curseforge.com/minecraft/mc-mods/distantfriends"
authors="Mrbysco, ShyNieke"
description='''
Don't mind them, they just like looking at you
'''
[[dependencies.distantfriends]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.6,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.distantfriends]]
modId="neoforge"
type="required"
versionRange="[20.6.78-beta,)"
ordering="NONE"
side="BOTH"